### ISSUE TITLE
Response headers are set to html when TypedRoute is used

### ISSUE THREAD

**Issue by ilterugur** [samchon/encrypted-nestjs#29]
Nestjs's default route methods (Get, Post, Put etc.) automatically sets the response's content type header to json if response returns json but nestia helper's TypedRoute methods set it to html. Is there any workaround or fix for this?

**Comment by samchon** [comment]
Thanks for reporting. `v3.0.8` update has fixed the bug.

  - `EncryptedRoute`: text/plain
  - `TypedRoute`: application/json
